### ISSUE TITLE
want to know shadow working flow

### ISSUE THREAD

**Issue by Raghav3107** [FreeRTOS/Lab-Project-coreMQTT-Agent#36]
Hello 

I was checking shadow demos code in the repository. They create two files one is to update the report state and another to update the desired state.
But to update the shadow we need to connect to the MQTT broker. I didn't see any code to connect to MQTT in shadow files.
Can anyone tell me the working flow of this repo?

**Comment by muneebahmed10** [comment]
Hi @Raghav3107,

The shadow demo (and every other demo in this repository) assume that the MQTT connection has already been created. Since all of the demos share the same MQTT connection, and multiple combinations of concurrent demos are possible, no one demo is responsible for setting up the connection. Instead, the MQTT connection is [created by the agent task](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/source/connection_manager.c#L514) (the task responsible for calling MQTTAgent_CommandLoop), since that task is common to every demo. Each demo references the MQTT connection used by the agent with a [global variable](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/source/shadow-tasks/shadow_device_task.c#L159). If you don't want to use global variables, it could also have been passed as a parameter at time of task creation.

Let us know if you have further questions.

**Comment by Raghav3107** [comment]
Hello @muneebahmed10 
Thanks for the explanation.

So, if we want to use shadow we need to write the program for the MQTT connection?
I want to use the report shadow and desire shadow in one file, can you suggest to me how shall I do that?
Also, how can I run these repos in Linux OS? Like in the official repo there is CMake files that are used to configure the libraries but I did not see any CMake file?

**Comment by muneebahmed10** [comment]
Hi @Raghav3107,

Yes, you need to write both the shadow and mqtt agent tasks. The MQTT agent API was designed so that application writers would have freedom in choosing how to handle error conditions and disconnects. The demo in this repo contains an example of [reconnect functionality](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/source/connection_manager.c#L882) after errors, but a user may decide to forego that, or add a task notification for disconnects, etc.

I'm not sure what you mean by having shadow in one file; as long as your files are able to [call the functions](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/source/connection_manager.c#L967) you write, they can be in one file or multiple; if you want everything in one file, you can just move it to that file.

We haven't added a Linux port nor do we use CMake in this repo, since the demos in this repository are FreeRTOS-specific and we have included the Visual Studio build files for the Windows simulator. The CMake files in the MQTT agent submodule are currently used when building unit tests, but they can be used if you want to use CMake in your project.

To use the agent in Linux, you would have to implement the functions used in its [messaging interface](https://github.com/FreeRTOS/coreMQTT-Agent/blob/main/source/include/mqtt_agent.h#L205), which includes functions to send and receive pointers in a thread-safe manner (for FreeRTOS, it's implemented using a [queue](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/lib/FreeRTOS/mqtt-agent-interface/freertos_agent_message.h#L51)), as well as functions to [allocate and release](https://github.com/FreeRTOS/Lab-Project-coreMQTT-Agent/blob/main/lib/FreeRTOS/mqtt-agent-interface/freertos_command_pool.c) the Command_t structures that are used by the agent to store command information. For Linux, the latter can just be malloc() and free() if you are willing to use dynamic allocation; the example here uses a pool with static allocation for cases where dynamic allocation may be undesirable. For the send and receive functions, you should have a thread safe implementation that preserves ordering. For example, you could write a linked list protected by a mutex, or use [POSIX message queues](https://man7.org/linux/man-pages/man7/mq_overview.7.html).

**Comment by Raghav3107** [comment]
Hello @muneebahmed10 
Thank you so much for the explanation and suggestion.

Actually, I want to write the code in such a way that when I make a change in the desired shadow in cloud, so delta will create, based on the delta, the desired shadow and report shadow should update simultaneously, just like the official shadow demos files.
